---
# Hosts tasks for puppet_common role

- name: Assert that gateway IP is defined
  ansible.builtin.assert:
    that: gateway_ip is defined
    msg: "Gateway IP is not defined"
  tags: [ "hosts", "puppet_common" ]

- name: Add hosts entry
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ gateway_ip }} {{ puppet_common_gateway_services }} # Added by Ansible Puppet Common installer"
    regexp: "^{{ gateway_ip }}\\s+{{ puppet_common_gateway_services }}"
  tags: [ "hosts", "puppet_common" ]

- name: Copy trusted certificates
  ansible.builtin.copy:
    src: certs/
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'
  loop:
    - /etc/ssl/certs
    - /usr/local/share/ca-certificates
  tags: [ "hosts", "puppet_common" ]

- name: Update certificate store
  ansible.builtin.command: "update-ca-certificates"
  ignore_errors: true
  tags: [ "hosts", "puppet_common" ]
