apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gogs.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  - port: 2211
    targetPort: 2211
    name: ssh