---
# Installation tasks for node_exporter role

- name: Create Node Exporter systemd service
  ansible.builtin.template:
    src: node_exporter_service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  tags: [ "install", "node_exporter" ]

- name: Enable and start Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [ "install", "node_exporter" ]
