---
# Setup tasks for node_exporter role

- name: Create user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    shell: /bin/false
    system: yes
    createhome: no
    state: present
  tags: [ "setup", "node_exporter" ]

- name: Create working directory
  ansible.builtin.file:
    path: "{{ node_exporter_working_directory }}"
    state: directory
    mode: "0755"
  tags: [ "setup", "node_exporter" ]

- name: Download binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_name }}.tar.gz"
    dest: "{{ node_exporter_working_directory }}/{{ node_exporter_name }}.tar.gz"
    mode: '0644'
  tags: [ "setup", "node_exporter" ]

- name: Extract binary
  ansible.builtin.unarchive:
    src: "{{ node_exporter_working_directory }}/{{ node_exporter_name }}.tar.gz"
    dest: "{{ node_exporter_working_directory }}"
    creates: "{{ node_exporter_working_directory }}/{{ node_exporter_name }}"
  tags: [ "setup", "node_exporter" ]
