---
# Main tasks file for puppet_server role

- name: Import common setup tasks
  ansible.builtin.import_tasks: setup.yml
  tags: [ "setup", "puppet_server" ]

- name: Import Puppet Server configuration tasks
  ansible.builtin.import_tasks: config.yml
  tags: [ "config", "puppet_server" ]

- name: Import Puppet Server service management tasks
  ansible.builtin.import_tasks: service.yml
  tags: [ "service", "puppet_server" ]

- name: Import PuppetDB installation tasks
  ansible.builtin.import_tasks: puppetdb.yml
  tags: [ "puppetdb", "puppet_server" ]

- name: Import environment deployment tasks
  ansible.builtin.import_tasks: environments.yml
  tags: [ "environments", "puppet_server" ]
