---
- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-pip
    state: present

- name: Install psycopg2
  ansible.builtin.pip:
    name: psycopg2-binary

- name: Install PuppetDB
  ansible.builtin.command: "/opt/puppetlabs/bin/puppet resource package puppetdb ensure=latest"

- name: Install PuppetDB Termini
  ansible.builtin.command: "/opt/puppetlabs/bin/puppet resource package puppetdb-termini ensure=latest"

- name: Create PuppetDB PostgreSQL user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ puppetdb.db.user }}"
    password: "{{ puppetdb.db.password }}"
    role_attr_flags: CREATEDB,LOGIN

- name: Create PuppetDB database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ puppetdb.db.name }}"
    owner: "{{ puppetdb.db.user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: Install pg_trgm extension in PuppetDB database
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    name: pg_trgm
    db: "{{ puppetdb.db.name }}"

- name: Configure database.ini
  ansible.builtin.template:
    src: database.ini.j2
    dest: /etc/puppetlabs/puppetdb/conf.d/database.ini
    owner: puppetdb
    group: puppetdb
    mode: "0640"

- name: Configure jetty.ini
  ansible.builtin.template:
    src: jetty.ini.j2
    dest: /etc/puppetlabs/puppetdb/conf.d/jetty.ini
    owner: puppetdb
    group: puppetdb
    mode: "0640"

- name: Configure PuppetDB connection for Puppet Server
  ansible.builtin.template:
    src: puppetdb.conf.j2
    dest: "{{ puppet.conf_dir }}/puppetdb.conf"
    owner: puppetdb
    group: puppetdb
    mode: "0640"

- name: Configure routes.yaml for PuppetDB
  ansible.builtin.template:
    src: routes.yaml.j2
    dest: "{{ puppet.conf_dir }}/routes.yaml"
    owner: puppetdb
    group: puppetdb
    mode: "0640"

- name: Start PuppetDB service
  ansible.builtin.command: "/opt/puppetlabs/bin/puppet resource service puppetdb ensure=running enable=true"

- name: Show PuppetDB status
  ansible.builtin.debug:
    msg: "PuppetDB installed and running at https://{{ certname }}:8081"
