apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gogs.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: ssh
    port: 2211
    targetPort: 2211
  type: ClusterIP
