---
galaxy_info:
  role_name: puppet_agent
  author: Krasnopolsky
  description: Installs and configures Puppet Agent on Ubuntu
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - puppet
    - agent
    - configuration
    - management

dependencies:
  - role: puppet_common
