apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.prepper.name }}
  namespace: {{ .Values.namespace }}
subsets:
  - addresses:
    - ip: {{ .Values.prepper.ip }}
    ports:
    - name: http
      port: 2021
