---
galaxy_info:
  role_name: node_exporter
  author: Krasnopolsky
  description: Installs and configures Node Exporter on Ubuntu
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - node_exporter
    - configuration
    - management
