---
# Main tasks file for puppet_agent role

- name: Import hosts tasks
  ansible.builtin.import_tasks: hosts.yml
  tags: [ "hosts", "puppet_agent" ]

- name: Import installation tasks
  ansible.builtin.import_tasks: install.yml
  tags: [ "install", "puppet_agent" ]

- name: Import configuration tasks
  ansible.builtin.import_tasks: config.yml
  tags: [ "config", "puppet_agent" ]

- name: Import service tasks
  ansible.builtin.import_tasks: service.yml
  tags: [ "service", "puppet_agent" ]
