---
- name: Assert that server IP and server certname are defined
  ansible.builtin.assert:
    that: server_ip is defined and server_certname is defined
    msg: "Server IP or server certname is not defined"

- name: Add hosts entry for Puppet Server
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ server_ip }} {{ server_certname }} # Added by Ansible Puppet Agent installer"
    regexp: "^{{ server_ip }}\\s+{{ server_certname }}"

- name: Install Puppet Agent
  ansible.builtin.apt:
    name: puppet-agent
    state: present

- name: Create Puppet configuration directory
  ansible.builtin.file:
    path: "{{ puppet_conf_dir }}"
    state: directory
    mode: "0755"

- name: Configure Puppet Agent
  ansible.builtin.template:
    src: puppet-agent.conf.j2
    dest: "{{ puppet_conf_dir }}/puppet.conf"
    mode: "0644"

- name: Request certificate signing
  ansible.builtin.command: "/opt/puppetlabs/bin/puppet agent --test --waitforcert {{ wait_for_cert }}"
  args:
    creates: "/etc/puppetlabs/puppet/ssl/certs/{{ certname }}.pem"
  changed_when: false
  failed_when: false

- name: Enable Puppet agent service
  ansible.builtin.systemd:
    name: puppet
    enabled: true

- name: Start Puppet agent service
  ansible.builtin.systemd:
    name: puppet
    state: started

- name: Show Puppet agent status
  ansible.builtin.debug:
    msg: "Puppet Agent installed and configured with certificate name: {{ certname }} connecting to server: {{ server_certname }}"
