---
services:
  gogs:
    hostname: gogs.local
    image: gogs/gogs:0.13-arm64
    ports:
      - "127.0.0.1:3000:3000"
      - "2211:2211"
    volumes:
      - ./config/app.ini:/data/gogs/conf/app.ini
      - gogs-data:/data
    networks:
      - devops
      - internal

  postgresql:
    image: postgres:17-alpine
    env_file:
      - ./config/.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  gogs-data:
  postgresql-data:

networks:
  internal:
  devops:
    external: true
